# fly.toml file generated for product-inventory on 2023-05-23T11:54:44-03:00

app = "product-inventory"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 120
processes = []

[env]
  APP_URL = "https://product-inventory.fly.dev"
  ENVIRONMENT = "production"
  MAINTENANCE = "false"
  DB_DRIVER = "mysql"
  DB_NAME = "product_inventory_db"
  DB_HOST = ""
  DB_PORT = ""
  CACHE_EXPIRATION_TIME = "30"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  image = "flyio/hellofly:latest"
  dockerfile = "Dockerfile.test"
  builder = "paketobuildpacks/builder:full"
  buildpacks = ["gcr.io/paketo-buildpacks/php"]

[mounts]
  source = "product_inventory_data"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
